project:
  type: website
  output-dir: docs

website:
  title: "ES-193DS"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: Class info

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



